name: Check
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependecyes
        run: yarn install
      - name: lint
        run: yarn eslint
      - name: test
        run: yarn test
      - name: prettier
        run: yarn prettier
